Update cmake-multi-platform.yml with exit code with no arg
We need to check if returning -1 is fine because it may provoke the action to exit

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -76,14 +76,15 @@ jobs:
       run: cmake --build build/ -j
     - name: Install with cmake
       run: sudo cmake --install build/
-    - name: Test shuriken-dump output
+    - name: Verify shuriken-dump exit code
       run: |
-        output=$(shuriken-dump)
-        expected="USAGE: shuriken-dump <file_to_analyze> [-h] [-c] [-f] [-m] [-b]\n\t-h: show file header\n\t-c: show classes from file\n\t-f: show fields from classes (it needs -c)\n\t-m: show methods from classes (it needs -c)\n\t-b: show bytecode from methods (it needs -m)\n\t-D: show the disassembled code from methods (it needs -m)"
-        if [ "$output" = "$expected" ]; then
-          echo "shuriken-dump is working correctly."
+        set +e # Prevent the script from exiting immediately on error
+        shuriken-dump
+        exit_code=$?
+        set -e # Re-enable immediate script exit on error
+        if [ $exit_code -eq 255 ]; then
+          echo "shuriken-dump exited with the expected exit code."
         else
-          echo "Unexpected output from shuriken-dump."
-          echo "Received: $output"
+          echo "Unexpected exit code from shuriken-dump: $exit_code"
           exit 1
         fi
